spring:
  profiles:
    active:
      -dev

---
spring:
     profiles: dev  #开发环境
     application:
       name: microservicecloud-config-atfanlei-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-atfanlei-test

